### ISSUE TITLE
Indicação de área com click 

### ISSUE THREAD

**Issue by mateus-azevedo** [Rhuan-Gonzaga/JogoMemoria_react#1]
Você pode adicionar um detalhe mostrando que é uma área "clickável" no projeto

Adicionando um ```cursor: pointer;``` na classe `.card_back` e no id `#restart`
https://github.com/Rhuan-Gonzaga/JogoMemoria_react/blob/0a15406a04cb6dcb576f1ab531c0176470c267c1/src/index.css#L73-L79

https://github.com/Rhuan-Gonzaga/JogoMemoria_react/blob/0a15406a04cb6dcb576f1ab531c0176470c267c1/src/index.css#L99-L106

**Comment by NaincyKumariKnoldus** [comment]
Ei @mateus-azevedo , eu adoraria adicionar isso. Posso?

**Comment by NaincyKumariKnoldus** [comment]
Olá eu levantei PR para isso. Por favor, reveja isso.
Obrigado!
Hello I have raised PR for this. Please review this.
Thanks!

**Comment by mateus-azevedo** [comment]
> Ei @mateus-azevedo , eu adoraria adicionar isso. Posso?

Com certeza!

**Comment by NaincyKumariKnoldus** [comment]
Ei @mateus-azevedo , por favor, revise e mescle meu PR.

**Comment by mateus-azevedo** [comment]
> Ei @mateus-azevedo , por favor, revise e mescle meu PR.

Eu revisei e tá tudo certinho. 
Mas quem tem permissão para fazer o merge é o @Rhuan-Gonzaga .

**Comment by NaincyKumariKnoldus** [comment]
Obrigada @mateus-azevedo 
Olá @Rhuan-Gonzaga , você pode revisar meu PR para isso?

**Comment by Rhuan-Gonzaga** [comment]
PR accepted, thanks!

**Comment by NaincyKumariKnoldus** [comment]
Thankyou so much @Rhuan-Gonzaga
